apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata: 
  name: {{ template "agents.name" . }}
spec:
  version: {{ .Values.version }}
  kibanaRef:
    name: {{ .Values.references.kibana }}
  fleetServerRef: 
    name: {{ .Values.references.fleetserver }}
  mode: fleet
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: {{ template "agents.serviceAccount" . }}
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
