version: 7.15.2

replicas: 1
kibanaName: kibana

nameOverride: ""
fullnameOverride: "my-kibana"

elasticsearchName: elasticsearch
elasticsearchNamespace: default

### If you are running Elasticsearch with ECK, keep this enabled, otherwise fill up the `kibanaSecretElasticsearchCredentials` & `elasticsearchEndpoint`
elasticsearchManagedbyECK:
  enabled: true

kibanaSecretElasticsearchCredentials: ""
elasticsearchEndpoint: ""

### If you are connecting Kibana with a Elasticsearch running out of ECK and it's using a self-signed cert, enable the option below
ElasticsearchSelfCertificate: 
  enabled: false

### Add here the secret name which contains the es certs
elasticsearchCertsSecret: ""
