version: 7.15.2
replicas: 1

# Make sure to use your own elasticsearch & kibana name (You can get it running: kubectl get es & kubectl get kibana)
references:
  elasticsearch:
    name: elasticsearch
  kibana:
    name: kibana

managedServiceAccount: true
serviceAccount: ""

clusterRoleRules:
  - apiGroups: [""]
    resources:
    - pods
    - nodes
    verbs:
    - get
    - watch
    - list
  - apiGroups: ["coordination.k8s.io"]
    resources:
    - leases
    verbs:
    - get
    - create
    - update
