apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ template "kibana.name" . }}
spec:
  version: {{ .Values.version }}
  count: {{ .Values.replicas }}
  {{- if .Values.elasticsearch.managedbyeck }}
  elasticsearchRef:
    name: {{ .Values.elasticsearch.name }}
    namespace: {{ .Values.elasticsearch.namespace }}
  {{ else }}
  config:
    elasticsearch.hosts:
      - {{ .Values.elasticsearch.endpoint }}
    elasticsearch.username: elastic
  secureSettings:
    - secretName: {{ .Values.elasticsearch.kibana.secretcredentials }}
  {{- end }}
  {{- if .Values.elasticsearch.certificate.enabled }}
  podTemplate:
    spec:
      volumes:
        - name: elasticsearch-certs
          secret:
            secretName:  {{ .Values.elasticsearch.certs.secret }}
      containers:
        - name: kibana
          volumeMounts:
            - name: elasticsearch-certs
              mountPath: /etc/certs
              readOnly: true   
  {{- end }}
  {{- if .Values.fleet.enabled }}
  config:
    xpack.fleet.agents.elasticsearch.host: {{ .Values.fleet.agents.hosts.elasticsearchhost }}
    xpack.fleet.agents.fleet_server.hosts: [{{ .Values.fleet.agents.hosts.fleetserverhost }}]
  {{- end }}

